"""delete association table

Revision ID: 6d840608bff2
Revises: e23e87ab65b0
Create Date: 2026-02-08 21:58:50.917346

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d840608bff2'
down_revision: str | Sequence[str] | None = 'e23e87ab65b0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_product_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users_product_association',
        sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            'created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False
        ),
        sa.Column(
            'updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ['product_id'], ['products.id'], name=op.f('users_product_association_product_id_fkey')
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('users_product_association_user_id_fkey')),
        sa.PrimaryKeyConstraint('id', name=op.f('users_product_association_pkey')),
    )
    # ### end Alembic commands ###
